# Generated by Django 3.2.4 on 2021-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(help_text='dscribe what to do', max_length=150, null=True),
        ),
    ]
