# Generated by Django 3.2.4 on 2021-06-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(help_text='describe what you want to do', max_length=150, null=True),
        ),
    ]
